# Generated by Django 3.0 on 2021-05-23 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymodel',
            name='date_submited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applymodel',
            name='linked_in_profile',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
