# Generated by Django 3.0 on 2021-05-23 16:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('itsite', '0003_auto_20210523_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='applymodel',
            name='github_profile_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applymodel',
            name='linkedin_profile_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
