# Generated by Django 3.0 on 2021-05-23 20:46

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('itsite', '0004_auto_20210523_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None)),
                ('message', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='documents')),
                ('date_submited', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
