# Generated by Django 3.0 on 2021-06-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsite', '0008_auto_20210607_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
