# Generated by Django 3.0 on 2021-06-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsite', '0010_auto_20210614_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymodel',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
