# Generated by Django 3.0 on 2021-06-19 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsite', '0012_auto_20210616_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applymodel',
            old_name='phone',
            new_name='full_number',
        ),
        migrations.RenameField(
            model_name='requestmodel',
            old_name='phone',
            new_name='full_number',
        ),
    ]
