# Generated by Django 3.0 on 2021-06-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsite', '0014_auto_20210619_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymodel',
            name='referer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='referer',
            field=models.URLField(blank=True, null=True),
        ),
    ]
